### PR TITLE
Update Gatsby Algolia plugin

### PR DESCRIPTION
**Pull request by bdenham**
## Description

This PR updates the `gatsby-plugin-algolia` plugin to version 0.26.0. I updated a few bits of the backend search code to accommodate this new version, mostly with record creation.

Here are the changes required as noted in the plugin's changelog: https://github.com/algolia/gatsby-plugin-algolia/blob/master/CHANGELOG.md

## Motivation and Context

Version 0.26.0 of the `gatsby-plugin-algolia` plugin fixes and simplifies how records are replaced in the index. Before, all the records were deleted from the index and replaced with all new records, regardless of whether the records had been changed. To be clear, the plugin had a flag (`enablePartialUpdates`) that was supposed to update only the records that changed, but it didn't work reliably. Version 0.26.0 fixes that by using `contentDigest`, which reflects some of the same techniques we used in the theme's search code. Now we can rely on the plugin to do this and simplify our code.

## How Has This Been Tested?

Ran indexing locally on the theme's example project. At the moment, it's building and replacing the same number of records in the Algolia indexes: 335 out of 433. This may be a case where we need to update the code on our side, but it's better. 

Also tested the changes against the `commerce-php` repo using `yalc` in the `search-test` branch: https://github.com/AdobeDocs/commerce-php/tree/search-test

You can pull down that branch and run the build using `ALGOLIA_INDEXATION_MODE=console` to see the results. 
As I suspected, the previous index size for `commerce-php` was much too large at 9,237. So I cleared it on the server and ran it again locally to get 666 records indexed. That's more like it. I ran the index again to make sure the records were not being duplicated as I suspected they were before and got the same 666 records indexed to Algolia.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
Sounds like a big improvement in indexing efficiency! Thanks for the detailed notes on testing @bdenham!

**Comment by bdenham** [comment]
FYI, here's something I noticed a while back that this update will fix: **growing indices**. On Algolia's servers, the current number of records in the `commerce-webapi` index is `7,288`. This morning before the latest index a few minutes ago, the number of records was `6,742`! 

So the old `gatsby-plugin-algolia` plugin and the old record-builder code are adding records. There's a records leak! So this PR fixes that.

**Comment by bdenham** [comment]
@dmitrymatio, if you can focus on the review and merging of this PR today, I can start clearing existing Algolia indices and reindexing certain sites/repos. Thanks!

**Comment by bdenham** [comment]
@dmitrymatio, @jeff-matthews, and @timkim: To clarify, the plugin update was a breaking change to our code base, but not to our indexing process. The process was adjusted/improved to accommodate the new plugin features.

**Review by timkim — APPROVED** [review]

**Pull request merged**
